# Generated by Django 5.2.3 on 2025-06-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('number', models.CharField(max_length=400)),
                ('content', models.TextField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
